sonar.projectKey=NoTIPswe_notip-simulator-backend
sonar.organization=notipswe

sonar.sources=internal
sonar.exclusions=**/*_test.go,vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.coverage.exclusions=internal/fakes/**,internal/adapters/http/dto/**,internal/app/app.go,internal/adapters/nats/**

sonar.go.coverage.reportPaths=coverage.out
