sonar.projectKey=NoTIPswe_notip-simulator-backend
sonar.organization=notipswe

sonar.sources=.
sonar.exclusions=**/*_test.go,vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
